// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scavenge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetCommitRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCommitRequest) Reset()         { *m = QueryGetCommitRequest{} }
func (m *QueryGetCommitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommitRequest) ProtoMessage()    {}
func (*QueryGetCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{0}
}
func (m *QueryGetCommitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommitRequest.Merge(m, src)
}
func (m *QueryGetCommitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommitRequest proto.InternalMessageInfo

func (m *QueryGetCommitRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCommitResponse struct {
	Commit *Commit `protobuf:"bytes,1,opt,name=Commit,proto3" json:"Commit,omitempty"`
}

func (m *QueryGetCommitResponse) Reset()         { *m = QueryGetCommitResponse{} }
func (m *QueryGetCommitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommitResponse) ProtoMessage()    {}
func (*QueryGetCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{1}
}
func (m *QueryGetCommitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommitResponse.Merge(m, src)
}
func (m *QueryGetCommitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommitResponse proto.InternalMessageInfo

func (m *QueryGetCommitResponse) GetCommit() *Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

type QueryAllCommitRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCommitRequest) Reset()         { *m = QueryAllCommitRequest{} }
func (m *QueryAllCommitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCommitRequest) ProtoMessage()    {}
func (*QueryAllCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{2}
}
func (m *QueryAllCommitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCommitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCommitRequest.Merge(m, src)
}
func (m *QueryAllCommitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCommitRequest proto.InternalMessageInfo

func (m *QueryAllCommitRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCommitResponse struct {
	Commit     []*Commit           `protobuf:"bytes,1,rep,name=Commit,proto3" json:"Commit,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCommitResponse) Reset()         { *m = QueryAllCommitResponse{} }
func (m *QueryAllCommitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCommitResponse) ProtoMessage()    {}
func (*QueryAllCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{3}
}
func (m *QueryAllCommitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCommitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCommitResponse.Merge(m, src)
}
func (m *QueryAllCommitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCommitResponse proto.InternalMessageInfo

func (m *QueryAllCommitResponse) GetCommit() []*Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *QueryAllCommitResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetScavengeRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetScavengeRequest) Reset()         { *m = QueryGetScavengeRequest{} }
func (m *QueryGetScavengeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetScavengeRequest) ProtoMessage()    {}
func (*QueryGetScavengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{4}
}
func (m *QueryGetScavengeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetScavengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetScavengeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetScavengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetScavengeRequest.Merge(m, src)
}
func (m *QueryGetScavengeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetScavengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetScavengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetScavengeRequest proto.InternalMessageInfo

func (m *QueryGetScavengeRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetScavengeResponse struct {
	Scavenge *Scavenge `protobuf:"bytes,1,opt,name=Scavenge,proto3" json:"Scavenge,omitempty"`
}

func (m *QueryGetScavengeResponse) Reset()         { *m = QueryGetScavengeResponse{} }
func (m *QueryGetScavengeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetScavengeResponse) ProtoMessage()    {}
func (*QueryGetScavengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{5}
}
func (m *QueryGetScavengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetScavengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetScavengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetScavengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetScavengeResponse.Merge(m, src)
}
func (m *QueryGetScavengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetScavengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetScavengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetScavengeResponse proto.InternalMessageInfo

func (m *QueryGetScavengeResponse) GetScavenge() *Scavenge {
	if m != nil {
		return m.Scavenge
	}
	return nil
}

type QueryAllScavengeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllScavengeRequest) Reset()         { *m = QueryAllScavengeRequest{} }
func (m *QueryAllScavengeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllScavengeRequest) ProtoMessage()    {}
func (*QueryAllScavengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{6}
}
func (m *QueryAllScavengeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllScavengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllScavengeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllScavengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllScavengeRequest.Merge(m, src)
}
func (m *QueryAllScavengeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllScavengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllScavengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllScavengeRequest proto.InternalMessageInfo

func (m *QueryAllScavengeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllScavengeResponse struct {
	Scavenge   []*Scavenge         `protobuf:"bytes,1,rep,name=Scavenge,proto3" json:"Scavenge,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllScavengeResponse) Reset()         { *m = QueryAllScavengeResponse{} }
func (m *QueryAllScavengeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllScavengeResponse) ProtoMessage()    {}
func (*QueryAllScavengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761e1fe4c505c12c, []int{7}
}
func (m *QueryAllScavengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllScavengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllScavengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllScavengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllScavengeResponse.Merge(m, src)
}
func (m *QueryAllScavengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllScavengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllScavengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllScavengeResponse proto.InternalMessageInfo

func (m *QueryAllScavengeResponse) GetScavenge() []*Scavenge {
	if m != nil {
		return m.Scavenge
	}
	return nil
}

func (m *QueryAllScavengeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCommitRequest)(nil), "cosmonaut.scavenge.scavenge.QueryGetCommitRequest")
	proto.RegisterType((*QueryGetCommitResponse)(nil), "cosmonaut.scavenge.scavenge.QueryGetCommitResponse")
	proto.RegisterType((*QueryAllCommitRequest)(nil), "cosmonaut.scavenge.scavenge.QueryAllCommitRequest")
	proto.RegisterType((*QueryAllCommitResponse)(nil), "cosmonaut.scavenge.scavenge.QueryAllCommitResponse")
	proto.RegisterType((*QueryGetScavengeRequest)(nil), "cosmonaut.scavenge.scavenge.QueryGetScavengeRequest")
	proto.RegisterType((*QueryGetScavengeResponse)(nil), "cosmonaut.scavenge.scavenge.QueryGetScavengeResponse")
	proto.RegisterType((*QueryAllScavengeRequest)(nil), "cosmonaut.scavenge.scavenge.QueryAllScavengeRequest")
	proto.RegisterType((*QueryAllScavengeResponse)(nil), "cosmonaut.scavenge.scavenge.QueryAllScavengeResponse")
}

func init() { proto.RegisterFile("scavenge/query.proto", fileDescriptor_761e1fe4c505c12c) }

var fileDescriptor_761e1fe4c505c12c = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x2d, 0x29, 0x76, 0x7a, 0x1b, 0x5a, 0x5b, 0xa2, 0x2c, 0xb2, 0x25, 0x56, 0x2c,
	0x99, 0xa1, 0x49, 0x7b, 0xf2, 0x14, 0x05, 0xeb, 0x51, 0x23, 0x5e, 0x04, 0x91, 0x49, 0x1c, 0xd6,
	0x85, 0xcd, 0xcc, 0xb6, 0x33, 0x29, 0x2d, 0xe2, 0xc5, 0x4f, 0x20, 0x78, 0x17, 0xbc, 0x14, 0xbc,
	0x08, 0x7e, 0x0b, 0x8f, 0x05, 0x2f, 0x1e, 0x25, 0xf1, 0x83, 0x48, 0x66, 0xde, 0x4e, 0x9a, 0x64,
	0xd9, 0x6e, 0x4a, 0x6f, 0x93, 0xd9, 0xf9, 0xff, 0xdf, 0xef, 0xfd, 0x67, 0x1e, 0xc1, 0xeb, 0xba,
	0xc7, 0x4f, 0x84, 0x8c, 0x04, 0x3b, 0x1a, 0x88, 0xe3, 0x33, 0x9a, 0x1e, 0x2b, 0xa3, 0xc8, 0x9d,
	0x9e, 0xd2, 0x7d, 0x25, 0xf9, 0xc0, 0xd0, 0xec, 0xbb, 0x5f, 0xd4, 0xee, 0x46, 0x4a, 0x45, 0x89,
	0x60, 0x3c, 0x8d, 0x19, 0x97, 0x52, 0x19, 0x6e, 0x62, 0x25, 0xb5, 0x93, 0xd6, 0x1e, 0x5a, 0xa9,
	0x66, 0x5d, 0xae, 0xc1, 0x93, 0x9d, 0xec, 0x75, 0x85, 0xe1, 0x7b, 0x2c, 0xe5, 0x51, 0x2c, 0xed,
	0x61, 0x38, 0xbb, 0xe1, 0x8b, 0xf7, 0x54, 0xbf, 0x1f, 0x1b, 0xd8, 0xde, 0xf4, 0xdb, 0xbe, 0xb8,
	0xfd, 0x10, 0x36, 0xf0, 0xc6, 0x8b, 0xb1, 0xe3, 0xa1, 0x30, 0x4f, 0xac, 0xa0, 0x23, 0x8e, 0x06,
	0x42, 0x1b, 0xb2, 0x8e, 0xab, 0xb1, 0x7c, 0x27, 0x4e, 0xb7, 0xd0, 0x3d, 0xf4, 0x60, 0xb5, 0xe3,
	0x7e, 0x84, 0xaf, 0xf0, 0xed, 0xd9, 0xe3, 0x3a, 0x55, 0x52, 0x0b, 0xf2, 0x08, 0xaf, 0xb8, 0x1d,
	0x2b, 0x58, 0x6b, 0x6e, 0xd3, 0x82, 0x86, 0x29, 0x88, 0x41, 0x12, 0xbe, 0x05, 0x8a, 0x76, 0x92,
	0x4c, 0x53, 0x3c, 0xc5, 0x78, 0xd2, 0x22, 0x38, 0xdf, 0x77, 0xce, 0x9a, 0x8e, 0xf3, 0xa0, 0x2e,
	0x63, 0xc8, 0x83, 0x3e, 0xe7, 0x91, 0x00, 0x6d, 0xe7, 0x92, 0x32, 0xfc, 0x8a, 0x00, 0xfc, 0x52,
	0x85, 0x1c, 0xf0, 0xe5, 0x05, 0xc1, 0xc9, 0xe1, 0x14, 0xdf, 0x92, 0xe5, 0xdb, 0xb9, 0x92, 0xcf,
	0x55, 0x9e, 0x02, 0x64, 0x78, 0x33, 0x0b, 0xf6, 0x25, 0xd4, 0x2a, 0xbe, 0x89, 0x37, 0x78, 0x6b,
	0x5e, 0x00, 0x2d, 0xb5, 0xf1, 0xad, 0x6c, 0x0f, 0x32, 0xab, 0x17, 0x36, 0xe5, 0x0d, 0xbc, 0x2c,
	0xe4, 0xc0, 0xd3, 0x4e, 0x92, 0x59, 0x9e, 0x9b, 0xba, 0x93, 0x73, 0x04, 0x2d, 0x4c, 0xd5, 0xc8,
	0x6d, 0x61, 0xf9, 0x1a, 0x2d, 0xdc, 0xd8, 0xdd, 0x34, 0x7f, 0x56, 0x71, 0xd5, 0x82, 0x92, 0x73,
	0x94, 0x3d, 0x16, 0xd2, 0x2c, 0xc4, 0xc9, 0x9d, 0xa9, 0x5a, 0x6b, 0x21, 0x8d, 0x23, 0x09, 0x5b,
	0x9f, 0x7e, 0xff, 0xfb, 0xb2, 0xd4, 0x20, 0xbb, 0xcc, 0x8b, 0xd9, 0xdc, 0x34, 0xc3, 0xb4, 0xb3,
	0x0f, 0xf6, 0x71, 0x7c, 0x24, 0xdf, 0x10, 0x5e, 0x75, 0x3e, 0xed, 0x24, 0x29, 0xc3, 0x3a, 0x3b,
	0x79, 0x65, 0x58, 0xe7, 0x66, 0x29, 0xdc, 0xb5, 0xac, 0x75, 0xb2, 0x5d, 0x82, 0x95, 0xfc, 0x40,
	0x93, 0x3b, 0x26, 0xfb, 0xa5, 0xa2, 0x99, 0x79, 0x8a, 0xb5, 0x83, 0x05, 0x55, 0x80, 0x79, 0x60,
	0x31, 0x19, 0x69, 0x14, 0x62, 0xfa, 0x45, 0x16, 0xea, 0x77, 0x84, 0xd7, 0x32, 0xaf, 0x71, 0xac,
	0xfb, 0xa5, 0x22, 0xba, 0x06, 0x73, 0xce, 0x40, 0x84, 0x0d, 0xcb, 0xbc, 0x43, 0xea, 0xa5, 0x98,
	0x1f, 0x3f, 0xfb, 0x35, 0x0c, 0xd0, 0xc5, 0x30, 0x40, 0x7f, 0x87, 0x01, 0xfa, 0x3c, 0x0a, 0x2a,
	0x17, 0xa3, 0xa0, 0xf2, 0x67, 0x14, 0x54, 0x5e, 0xd3, 0x28, 0x36, 0xef, 0x07, 0x5d, 0xda, 0x53,
	0xfd, 0x3c, 0xab, 0xd3, 0xc9, 0xd2, 0x9c, 0xa5, 0x42, 0x77, 0x57, 0xec, 0x1f, 0x45, 0xeb, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x67, 0x88, 0x1d, 0xd7, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a commit by index.
	Commit(ctx context.Context, in *QueryGetCommitRequest, opts ...grpc.CallOption) (*QueryGetCommitResponse, error)
	// Queries a list of commit items.
	CommitAll(ctx context.Context, in *QueryAllCommitRequest, opts ...grpc.CallOption) (*QueryAllCommitResponse, error)
	// Queries a scavenge by index.
	Scavenge(ctx context.Context, in *QueryGetScavengeRequest, opts ...grpc.CallOption) (*QueryGetScavengeResponse, error)
	// Queries a list of scavenge items.
	ScavengeAll(ctx context.Context, in *QueryAllScavengeRequest, opts ...grpc.CallOption) (*QueryAllScavengeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Commit(ctx context.Context, in *QueryGetCommitRequest, opts ...grpc.CallOption) (*QueryGetCommitResponse, error) {
	out := new(QueryGetCommitResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.scavenge.scavenge.Query/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CommitAll(ctx context.Context, in *QueryAllCommitRequest, opts ...grpc.CallOption) (*QueryAllCommitResponse, error) {
	out := new(QueryAllCommitResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.scavenge.scavenge.Query/CommitAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Scavenge(ctx context.Context, in *QueryGetScavengeRequest, opts ...grpc.CallOption) (*QueryGetScavengeResponse, error) {
	out := new(QueryGetScavengeResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.scavenge.scavenge.Query/Scavenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ScavengeAll(ctx context.Context, in *QueryAllScavengeRequest, opts ...grpc.CallOption) (*QueryAllScavengeResponse, error) {
	out := new(QueryAllScavengeResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.scavenge.scavenge.Query/ScavengeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a commit by index.
	Commit(context.Context, *QueryGetCommitRequest) (*QueryGetCommitResponse, error)
	// Queries a list of commit items.
	CommitAll(context.Context, *QueryAllCommitRequest) (*QueryAllCommitResponse, error)
	// Queries a scavenge by index.
	Scavenge(context.Context, *QueryGetScavengeRequest) (*QueryGetScavengeResponse, error)
	// Queries a list of scavenge items.
	ScavengeAll(context.Context, *QueryAllScavengeRequest) (*QueryAllScavengeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Commit(ctx context.Context, req *QueryGetCommitRequest) (*QueryGetCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedQueryServer) CommitAll(ctx context.Context, req *QueryAllCommitRequest) (*QueryAllCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitAll not implemented")
}
func (*UnimplementedQueryServer) Scavenge(ctx context.Context, req *QueryGetScavengeRequest) (*QueryGetScavengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scavenge not implemented")
}
func (*UnimplementedQueryServer) ScavengeAll(ctx context.Context, req *QueryAllScavengeRequest) (*QueryAllScavengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScavengeAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.scavenge.scavenge.Query/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Commit(ctx, req.(*QueryGetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CommitAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.scavenge.scavenge.Query/CommitAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitAll(ctx, req.(*QueryAllCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Scavenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetScavengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Scavenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.scavenge.scavenge.Query/Scavenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Scavenge(ctx, req.(*QueryGetScavengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ScavengeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllScavengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ScavengeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.scavenge.scavenge.Query/ScavengeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ScavengeAll(ctx, req.(*QueryAllScavengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.scavenge.scavenge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _Query_Commit_Handler,
		},
		{
			MethodName: "CommitAll",
			Handler:    _Query_CommitAll_Handler,
		},
		{
			MethodName: "Scavenge",
			Handler:    _Query_Scavenge_Handler,
		},
		{
			MethodName: "ScavengeAll",
			Handler:    _Query_ScavengeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scavenge/query.proto",
}

func (m *QueryGetCommitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCommitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Commit != nil {
		{
			size, err := m.Commit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCommitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCommitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCommitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCommitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCommitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCommitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Commit) > 0 {
		for iNdEx := len(m.Commit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Commit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetScavengeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetScavengeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetScavengeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetScavengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetScavengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetScavengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Scavenge != nil {
		{
			size, err := m.Scavenge.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllScavengeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllScavengeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllScavengeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllScavengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllScavengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllScavengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Scavenge) > 0 {
		for iNdEx := len(m.Scavenge) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Scavenge[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCommitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCommitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Commit != nil {
		l = m.Commit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCommitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCommitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Commit) > 0 {
		for _, e := range m.Commit {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetScavengeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetScavengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Scavenge != nil {
		l = m.Scavenge.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllScavengeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllScavengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Scavenge) > 0 {
		for _, e := range m.Scavenge {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCommitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCommitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Commit == nil {
				m.Commit = &Commit{}
			}
			if err := m.Commit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCommitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCommitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCommitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCommitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCommitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCommitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commit = append(m.Commit, &Commit{})
			if err := m.Commit[len(m.Commit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetScavengeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetScavengeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetScavengeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetScavengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetScavengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetScavengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scavenge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Scavenge == nil {
				m.Scavenge = &Scavenge{}
			}
			if err := m.Scavenge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllScavengeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllScavengeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllScavengeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllScavengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllScavengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllScavengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scavenge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scavenge = append(m.Scavenge, &Scavenge{})
			if err := m.Scavenge[len(m.Scavenge)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
